# Generated by Django 3.1 on 2020-09-06 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('category_image', models.ImageField(upload_to='category_image')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=50)),
                ('subcategory_image', models.ImageField(upload_to='subcategory_image')),
                ('categorys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winter.categorys')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_image', models.ImageField(upload_to='product_image')),
                ('product_price', models.IntegerField()),
                ('product_desc', models.CharField(max_length=300)),
                ('categorys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winter.categorys')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winter.subcategory')),
            ],
        ),
    ]
