# Generated by Django 3.1 on 2020-09-17 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winter', '0002_register'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='register',
            table='register',
        ),
    ]
