# Generated by Django 3.1 on 2020-09-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winter', '0004_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
