# Generated by Django 3.1 on 2020-09-21 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winter', '0006_cart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
    ]
