# Generated by Django 3.1 on 2020-10-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winter', '0009_address_order_ordernumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordernumber',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
